### ISSUE TITLE
是否可以利用 gobject-consume 项目

### ISSUE THREAD

**Issue by cheese** [linuxdeepin/gio-qt#15]
这个项目想通过 gir 自动生成 Qt binding，但是后来没有继续开发。如果能完善这个，就不需要单独为某个库写 binding
https://wiki.gnome.org/action/show/Projects/GObjectIntrospection/GObjectConsume?action=show&redirect=GObjectIntrospection%2FGObjectConsume
https://websvn.kde.org/trunk/playground/bindings/gobject-consume/

**Comment by BLumia** [comment]
自动生成 Qt binding 是个挺好的方案，目前 `gio-qt` 其实是文件管理器重构过程独立出来的代码，加上这个项目只会覆盖常用的 gio 的接口而不是整个 gtk ，稳妥起见没有选择生成代码这种方案（也因为我对 gtk 的工具不是那么熟悉），如果时间充足的话以后会去调研一下 `gobject-consume`。

不过按之前了解到的信息，glibmm/gtkmm 也是靠 gir 生成代码并手动处理遇到的问题，而在做 `gio-qt`的时候也还是遇到了 glibmm 的一些问题（[这个](https://gitlab.gnome.org/GNOME/glibmm/issues/50)，[待 patch 的包](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=932950)），因为不熟悉所以我不确定这个问题是不是生成代码导致的，待有时间后进一步研究。

**Comment by cheese** [comment]
Qt binding 又依赖 glibmm 感觉有点绕～
反正这个只是当作沟通，我就关了这个 issue

**Comment by BLumia** [comment]
:joy: 对，也是因为时间不宽裕所以选了包 glibmm 的方案，最初的主要目标是分离文管逻辑降低维护的复杂程度，也便于测试。

回头我更新一下 readme 提一下 `gobject-consume` ，是很好的方向。

感谢建议～

**Comment by cheese** [comment]
现在感大势是要做成纯 Qt，或许更应该把 gio 的功能都替换成 Qt-native 的库

**Comment by BLumia** [comment]
> 现在感大势是要做成纯 Qt，或许更应该把 gio 的功能都替换成 Qt-native 的库

其实已经逐步换掉一部分 `gio` 的功能改直接使用 `udisks` 了（[`udisks2-qt5`](https://github.com/linuxdeepin/udisks2-qt5) 也是这个过程独立出来的代码），而目前依然打算留 `gio` 的地方是网络设备的挂载访问支持，比如 samba ftp mtp 之类，没有单纯的 Qt 库供使用（如果不用 kio 的话），分别单独去支持的话开发资源消耗也会很大。
